### PR TITLE
Make sed calls portable

### PR DESCRIPTION
**Pull request by ghost**
Unlike GNU sed, FreeBSD sed requires an argument when passed -i.

While I think it is harmless, the configure scripts prints out the
following error on FreeBSD

sed: 1: "display.c": extra characters at the end of d command

While sed -i '' would work on FreeBSD, gsed -i '' is not the same.

### CODE REVIEW

**Comment by ibara** [comment]
This is not (strictly) a GNU sed vs. FreeBSD sed difference. OpenBSD sed also works like GNU sed, which is probably why I figured it worked the same everywhere else.

The FreeBSD manual page for sed says "If a zero-length extension is given, no backup will be saved." which is also why I thought this was safe.

If we're going to go this direction, `make distclean` should also remove those .bak files.

**Comment by ghost** [comment]
> The FreeBSD manual page for sed says "If a zero-length extension is given, no backup will be saved." which is also why I thought this was safe.

Yeah, but that is meant literally with an empty argument a la `-i ''` for some weird reason. It is annoying that FreeBSD's sed(1) behaves that way. This is not the first time I had to "fix" something like this.

> If we're going to go this direction, `make distclean` should also remove those .bak files.

Done.

**Comment by ibara** [comment]
Strange. But ok let's do this.
Thanks.

**Comment by ghost** [comment]
Thanks for merging.

For the record, I filed a bug against FreeBSD sed: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254091

**Pull request merged**
